<?php
$securitySettings_var = array( 'providers' => array( array( 'type' => '%db',
'activationField' => 'active',
'active' => true,
'code' => '01',
'codeField' => '',
'emailField' => 'usr_email',
'extUserIdField' => 'ext_security_id',
'fullnameField' => 'usr_name',
'label' => array( 'text' => 'Database',
'type' => 0 ),
'name' => 'db',
'passwordField' => 'Password',
'phoneField' => 'phone1',
'resetDateField' => 'reset_date',
'resetTokenField' => 'reset_token',
'table' => array( 'connId' => 'dbusers_at_localhost',
'table' => 'global_users' ),
'twoFactorField' => '',
'userGroupField' => 'groupid',
'usernameField' => 'Username',
'userpicField' => 'userpic' ) ),
'sessionControl' => array( 'lifeTime' => 15,
'sessionName' => 'FNnt4D7qPY1XyKf6dyOK',
'JWTSecret' => '8OirhmZH0VTJ1YzHKfnX' ),
'registration' => array( 'passwordValidation' => array( 'strong' => true,
'minimumLength' => 8,
'uniqueCharacters' => 4,
'digitsAndSymbols' => 2,
'upperAndLowerCase' => true ),
'remindMethod' => 1,
'hashAlgorithm' => 1,
'adminEmail' => '',
'caseInsensitiveLogin' => false,
'changePasswordPage' => true,
'changePwdPage' => true,
'hashPassword' => true,
'notifyAdmin' => false,
'notifyUser' => false,
'registerPage' => false,
'remindPage' => true,
'remindPasswordPage' => false,
'sendActivationLink' => false ),
'captchaSettings' => array( 'captchaType' => 0,
'siteKey' => '',
'secretKey' => '',
'passesCount' => 5 ),
'emailSettings' => array( 'fromEmail' => 'gestion@mincit.gov.co',
'usePHPDefinedSMTP' => false,
'useBuiltInMailer' => false,
'SMTPServer' => 'smtp.office365.com',
'SMTPPort' => 587,
'SMTPUser' => 'gestion@mincit.gov.co',
'SMTPPassword' => 'Mincomercio2021*',
'securityProtocol' => 2 ),
'advancedSecurity' => array( 'allowGuestLogin' => false ),
'auditAndLocking' => array( 'loggingTable' => array( 'connId' => 'edl_at_localhost',
'table' => 'gestionentidad_v106_audit' ),
'lockingTable' => array( 'connId' => 'edl_at_localhost',
'table' => 'gestionentidad_v106_locking' ),
'tables' => array( 'admin_members' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'admin_rights' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'admin_users' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'cargo' => array( 'logFieldValues' => false,
'logModifications' => false,
'recordLocking' => false ),
'contractor_master' => array( 'logFieldValues' => false,
'logModifications' => false,
'recordLocking' => false ),
'contractor_master_SJ' => array( 'logFieldValues' => false,
'logModifications' => false,
'recordLocking' => false ),
'contrato' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'contrato_attached_type' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'contrato_estados' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'contrato_forma_pago' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'contrato_natjuridica' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'contrato_pre' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'contrato_tipo' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'contrato_tipo_unidad' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'dependencia' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'dependencia_SJ' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'dependencia_det' => array( 'logFieldValues' => false,
'logModifications' => false,
'recordLocking' => false ),
'dependencia_det_DIR' => array( 'logFieldValues' => false,
'logModifications' => false,
'recordLocking' => false ),
'dependencias_001' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'divipola' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'ep_agregada' => array( 'logFieldValues' => false,
'logModifications' => false,
'recordLocking' => false ),
'ep_compromisos' => array( 'logFieldValues' => false,
'logModifications' => false,
'recordLocking' => false ),
'ep_obligaciones' => array( 'logFieldValues' => false,
'logModifications' => false,
'recordLocking' => false ),
'funcionario' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'funcionario_SJ' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'global_ejecucion' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'global_month' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'global_rol_almacen' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'global_rol_c' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'global_status' => array( 'logFieldValues' => false,
'logModifications' => false,
'recordLocking' => false ),
'global_users' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'global_users_contratistas' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'interventor_periodos' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'nombramiento' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'perfil' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'polizas_aseguradoras' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'polizas_tipo' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'q_graph_001' => array( 'logFieldValues' => false,
'logModifications' => false,
'recordLocking' => false ),
'q_graph_002' => array( 'logFieldValues' => false,
'logModifications' => false,
'recordLocking' => false ),
'rep_prg001_catalogopresupuestal' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tipo_banco' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tipo_cta_banco' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tipo_docidentidad' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tipo_liquidacion' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tparam_cajacomp' => array( 'logFieldValues' => false,
'logModifications' => false,
'recordLocking' => false ),
'tparam_estados' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tparam_estcivil' => array( 'logFieldValues' => false,
'logModifications' => false,
'recordLocking' => false ),
'tparam_fondopension' => array( 'logFieldValues' => false,
'logModifications' => false,
'recordLocking' => false ),
'tparam_fondosalud' => array( 'logFieldValues' => false,
'logModifications' => false,
'recordLocking' => false ),
'tparam_sn' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tparam_tipo_ct_000' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tparam_tipo_ct_001' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tparam_tipo_ct_002' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ),
'tparam_tipo_ct_arl' => array( 'logFieldValues' => false,
'logModifications' => false,
'recordLocking' => false ),
'tparam_tiporubro' => array( 'logFieldValues' => false,
'logModifications' => false,
'recordLocking' => false ),
'vigencia' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => true ) ),
'loggingMode' => 1,
'loggingFile' => 'audit.log',
'logSecurityActions' => true,
'lockAfterUnsuccessfulLogin' => true,
'enableLocking' => true ),
'twoFactorSettings' => array( 'available' => false,
'required' => false,
'enable' => true,
'remember' => true,
'types' => array(  ),
'twoFactorField' => '',
'emailField' => '',
'phoneField' => '',
'codeField' => '',
'projectName' => '' ),
'projectName' => 'GestionEntidad_v106',
'loginDataSource' => 'global_users',
'loginForm' => 1,
'dynamicPermissions' => true,
'dpTablePrefix' => 'gestionentidad_ver_106_',
'dpTableConnId' => 'edl_at_localhost',
'hardcodedLogin' => false,
'enabled' => true,
'advancedSecurityAvailable' => true,
'userGroupsAvailable' => true,
'defaultProviderCode' => '01',
'adOnlyLogin' => false,
'dbProvider' => array( 'type' => '%db',
'activationField' => 'active',
'active' => true,
'code' => '01',
'codeField' => '',
'emailField' => 'usr_email',
'extUserIdField' => 'ext_security_id',
'fullnameField' => 'usr_name',
'label' => array( 'text' => 'Database',
'type' => 0 ),
'name' => 'db',
'passwordField' => 'Password',
'phoneField' => 'phone1',
'resetDateField' => 'reset_date',
'resetTokenField' => 'reset_token',
'table' => array( 'connId' => 'dbusers_at_localhost',
'table' => 'global_users' ),
'twoFactorField' => '',
'userGroupField' => 'groupid',
'usernameField' => 'Username',
'userpicField' => 'userpic' ),
'adAdminGroups' => array(  ),
'showUserSource' => false,
'dbProviderCodes' => array( '01' ) );
?>